// Generated by gencpp from file dinogenerator/GenerateDinoRequest.msg
// DO NOT EDIT!


#ifndef DINOGENERATOR_MESSAGE_GENERATEDINOREQUEST_H
#define DINOGENERATOR_MESSAGE_GENERATEDINOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dinogenerator
{
template <class ContainerAllocator>
struct GenerateDinoRequest_
{
  typedef GenerateDinoRequest_<ContainerAllocator> Type;

  GenerateDinoRequest_()
    : input_word()  {
    }
  GenerateDinoRequest_(const ContainerAllocator& _alloc)
    : input_word(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _input_word_type;
  _input_word_type input_word;





  typedef boost::shared_ptr< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateDinoRequest_

typedef ::dinogenerator::GenerateDinoRequest_<std::allocator<void> > GenerateDinoRequest;

typedef boost::shared_ptr< ::dinogenerator::GenerateDinoRequest > GenerateDinoRequestPtr;
typedef boost::shared_ptr< ::dinogenerator::GenerateDinoRequest const> GenerateDinoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dinogenerator::GenerateDinoRequest_<ContainerAllocator1> & lhs, const ::dinogenerator::GenerateDinoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input_word == rhs.input_word;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dinogenerator::GenerateDinoRequest_<ContainerAllocator1> & lhs, const ::dinogenerator::GenerateDinoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dinogenerator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "94764fe0a557e76ab7754bb2cc9b8c17";
  }

  static const char* value(const ::dinogenerator::GenerateDinoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x94764fe0a557e76aULL;
  static const uint64_t static_value2 = 0xb7754bb2cc9b8c17ULL;
};

template<class ContainerAllocator>
struct DataType< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dinogenerator/GenerateDinoRequest";
  }

  static const char* value(const ::dinogenerator::GenerateDinoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input_word\n"
;
  }

  static const char* value(const ::dinogenerator::GenerateDinoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_word);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateDinoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dinogenerator::GenerateDinoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dinogenerator::GenerateDinoRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_word: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.input_word);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DINOGENERATOR_MESSAGE_GENERATEDINOREQUEST_H
