// Generated by gencpp from file dinogenerator/GenerateDinoResponse.msg
// DO NOT EDIT!


#ifndef DINOGENERATOR_MESSAGE_GENERATEDINORESPONSE_H
#define DINOGENERATOR_MESSAGE_GENERATEDINORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dinogenerator
{
template <class ContainerAllocator>
struct GenerateDinoResponse_
{
  typedef GenerateDinoResponse_<ContainerAllocator> Type;

  GenerateDinoResponse_()
    : output_dino_name()  {
    }
  GenerateDinoResponse_(const ContainerAllocator& _alloc)
    : output_dino_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _output_dino_name_type;
  _output_dino_name_type output_dino_name;





  typedef boost::shared_ptr< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateDinoResponse_

typedef ::dinogenerator::GenerateDinoResponse_<std::allocator<void> > GenerateDinoResponse;

typedef boost::shared_ptr< ::dinogenerator::GenerateDinoResponse > GenerateDinoResponsePtr;
typedef boost::shared_ptr< ::dinogenerator::GenerateDinoResponse const> GenerateDinoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dinogenerator::GenerateDinoResponse_<ContainerAllocator1> & lhs, const ::dinogenerator::GenerateDinoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output_dino_name == rhs.output_dino_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dinogenerator::GenerateDinoResponse_<ContainerAllocator1> & lhs, const ::dinogenerator::GenerateDinoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dinogenerator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5271d2fbe0b13e029f99697eea64afeb";
  }

  static const char* value(const ::dinogenerator::GenerateDinoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5271d2fbe0b13e02ULL;
  static const uint64_t static_value2 = 0x9f99697eea64afebULL;
};

template<class ContainerAllocator>
struct DataType< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dinogenerator/GenerateDinoResponse";
  }

  static const char* value(const ::dinogenerator::GenerateDinoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output_dino_name\n"
"\n"
;
  }

  static const char* value(const ::dinogenerator::GenerateDinoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output_dino_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateDinoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dinogenerator::GenerateDinoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dinogenerator::GenerateDinoResponse_<ContainerAllocator>& v)
  {
    s << indent << "output_dino_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.output_dino_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DINOGENERATOR_MESSAGE_GENERATEDINORESPONSE_H
