// Generated by gencpp from file dinogenerator/GenerateDino.msg
// DO NOT EDIT!


#ifndef DINOGENERATOR_MESSAGE_GENERATEDINO_H
#define DINOGENERATOR_MESSAGE_GENERATEDINO_H

#include <ros/service_traits.h>


#include <dinogenerator/GenerateDinoRequest.h>
#include <dinogenerator/GenerateDinoResponse.h>


namespace dinogenerator
{

struct GenerateDino
{

typedef GenerateDinoRequest Request;
typedef GenerateDinoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateDino
} // namespace dinogenerator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dinogenerator::GenerateDino > {
  static const char* value()
  {
    return "05f0b075fa1cdfa5ea65f04d56a877bc";
  }

  static const char* value(const ::dinogenerator::GenerateDino&) { return value(); }
};

template<>
struct DataType< ::dinogenerator::GenerateDino > {
  static const char* value()
  {
    return "dinogenerator/GenerateDino";
  }

  static const char* value(const ::dinogenerator::GenerateDino&) { return value(); }
};


// service_traits::MD5Sum< ::dinogenerator::GenerateDinoRequest> should match
// service_traits::MD5Sum< ::dinogenerator::GenerateDino >
template<>
struct MD5Sum< ::dinogenerator::GenerateDinoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dinogenerator::GenerateDino >::value();
  }
  static const char* value(const ::dinogenerator::GenerateDinoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dinogenerator::GenerateDinoRequest> should match
// service_traits::DataType< ::dinogenerator::GenerateDino >
template<>
struct DataType< ::dinogenerator::GenerateDinoRequest>
{
  static const char* value()
  {
    return DataType< ::dinogenerator::GenerateDino >::value();
  }
  static const char* value(const ::dinogenerator::GenerateDinoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dinogenerator::GenerateDinoResponse> should match
// service_traits::MD5Sum< ::dinogenerator::GenerateDino >
template<>
struct MD5Sum< ::dinogenerator::GenerateDinoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dinogenerator::GenerateDino >::value();
  }
  static const char* value(const ::dinogenerator::GenerateDinoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dinogenerator::GenerateDinoResponse> should match
// service_traits::DataType< ::dinogenerator::GenerateDino >
template<>
struct DataType< ::dinogenerator::GenerateDinoResponse>
{
  static const char* value()
  {
    return DataType< ::dinogenerator::GenerateDino >::value();
  }
  static const char* value(const ::dinogenerator::GenerateDinoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DINOGENERATOR_MESSAGE_GENERATEDINO_H
